php:
  preset: laravel
  version: 8.1
  disabled:
    - no_unused_imports
  finder:
    exclude:
      - "node_modules"
      - "storage"
      - "vendor"
    not-name:
      - index.php
js:
  finder:
    not-name:
      - webpack.mix.js
css: true
